First, import the usual libraries
- `math`: basic math operations
- `os`: enable file manipulation with the OS
- `sys`: enable interaction with commandline
- `glob`: more variable manipulation
- `matplotlib.pyplot`: default plotter (I personally like ggplot waaaaay better. E)
    - `inline`: so that plots are shown in the notebook
- `seaborn`: nicer plots
- `numpy`: all number cruching done here
- `pandas`: data wrangling

In [3]:
import math  
import os   
import glob 
import matplotlib.pyplot as plt 
%matplotlib inline
import seaborn as sns
import numpy as np
import pandas as pd
from scipy import stats

In [22]:
# Path to the folder where all the raw data is located
src = '/home/ejam/documents/css893/raw_data/'

# Path where we will save outputs
dst = '/home/ejam/documents/css893/output/'

# Matrix with raw SNP data
#file_snp_raw = 'snp_imputed_chr10_sample.csv'

# Matrix with imputed SNP data
file_snp_imp = '1231.txt'

# Matrix with gene expression (FPKM)
file_gen_high_z = 'high_ztpm.csv'

file_snp_high_z = 'high_z_snps_all_chr.csv'

We only need the gene regions right now. Ignore the zTPM values. This saves a lot of memory.

In [58]:
snp_high_z = pd.read_csv(src+file_snp_high_z, usecols=['gene','chrom', 'pos'])
#gen_high_z = gen_high_z.drop(columns='Unnamed: 0')
snp_high_z

                gene  chrom        pos
0     Zm00001d027457      1    5698946
1     Zm00001d027457      1    5698973
2     Zm00001d027457      1    5698991
3     Zm00001d027457      1    5698994
4     Zm00001d027457      1    5699162
...              ...    ...        ...
4032  Zm00001d026509     10  147354710
4033  Zm00001d026509     10  147354719
4034  Zm00001d026509     10  147354742
4035  Zm00001d026509     10  147354782
4036  Zm00001d026509     10  147354788

[4037 rows x 3 columns]

In [59]:
snp_high_z['rs'] = 'rs' + snp_high_z.chrom.map(str) + '_' + snp_high_z.pos.map(str)
high_rs = list(snp_high_z['rs'].values)
snp_high_z

                gene  chrom        pos              rs
0     Zm00001d027457      1    5698946     rs1_5698946
1     Zm00001d027457      1    5698973     rs1_5698973
2     Zm00001d027457      1    5698991     rs1_5698991
3     Zm00001d027457      1    5698994     rs1_5698994
4     Zm00001d027457      1    5699162     rs1_5699162
...              ...    ...        ...             ...
4032  Zm00001d026509     10  147354710  rs10_147354710
4033  Zm00001d026509     10  147354719  rs10_147354719
4034  Zm00001d026509     10  147354742  rs10_147354742
4035  Zm00001d026509     10  147354782  rs10_147354782
4036  Zm00001d026509     10  147354788  rs10_147354788

[4037 rows x 4 columns]

sample

In [6]:
sample_snps = []
with open(src+file_snp_imp) as f:
    for i in range(11):
        sample_snps.append(f.readline())

In [12]:
sample_snps[0].split('\t')

['<Marker>',
 'rs1_44306',
 'rs1_44441',
 'rs1_44879',
 'rs1_45948',
 'rs1_46521',
 'rs1_46538',
 'rs1_47157',
 'rs1_47221',
 'rs1_47854',
 'rs1_47872',
 'rs1_48071',
 'rs1_48081',
 'rs1_48140',
 'rs1_48208',
 'rs1_48213',
 'rs1_48381',
 'rs1_48395',
 'rs1_48548',
 'rs1_48714',
 'rs1_48831',
 'rs1_48879',
 'rs1_48890',
 'rs1_48910',
 'rs1_48921',
 'rs1_49094',
 'rs1_49346',
 'rs1_49372',
 'rs1_49373',
 'rs1_49498',
 'rs1_49527',
 'rs1_49616',
 'rs1_51021',
 'rs1_51037',
 'rs1_51053',
 'rs1_51898',
 'rs1_52753',
 'rs1_52778',
 'rs1_53064',
 'rs1_53109',
 'rs1_53802',
 'rs1_55279',
 'rs1_55373',
 'rs1_55419',
 'rs1_55449',
 'rs1_55589',
 'rs1_55654',
 'rs1_55664',
 'rs1_56073',
 'rs1_56125',
 'rs1_108937',
 'rs1_109011',
 'rs1_109355',
 'rs1_138573',
 'rs1_139436',
 'rs1_153876',
 'rs1_154000',
 'rs1_154048',
 'rs1_155203',
 'rs1_155222',
 'rs1_172236',
 'rs1_172386',
 'rs1_172600',
 'rs1_172806',
 'rs1_172921',
 'rs1_173202',
 'rs1_173287',
 'rs1_173317',
 'rs1_173324',
 'rs1_173480',
 'rs1_173809',
 'rs1_173812',
 'rs1_174153',
 'rs1_174183',
 'rs1_174374',
 'rs1_174382',
 'rs1_174587',
 'rs1_174590',
 'rs1_174731',
 'rs1_174778',
 'rs1_174856',
 'rs1_174932',
 'rs1_174963',
 'rs1_175150',
 'rs1_175234',
 'rs1_175248',
 'rs1_175544',
 'rs1_175697',
 'rs1_176007',
 'rs1_176010',
 'rs1_176215',
 'rs1_176320',
 'rs1_176687',
 'rs1_176689',
 'rs1_176756',
 'rs1_176846',
 'rs1_176878',
 'rs1_176892',
 'rs1_176919',
 'rs1_176941',
 'rs1_177012',
 'rs1_177035',
 'rs1_177048',
 'rs1_177094',
 'rs1_180544',
 'rs1_180618',
 'rs1_180622',
 'rs1_180765',
 'rs1_180838',
 'rs1_181149',
 'rs1_181209',
 'rs1_181212',
 'rs1_181448',
 'rs1_197213',
 'rs1_197229',
 'rs1_197233',
 'rs1_197268',
 'rs1_197269',
 'rs1_197287',
 'rs1_197309',
 'rs1_197339',
 'rs1_197508',
 'rs1_197580',
 'rs1_197726',
 'rs1_197847',
 'rs1_197848',
 'rs1_197923',
 'rs1_198046',
 'rs1_198234',
 'rs1_198300',
 'rs1_198310',
 'rs1_198825',
 'rs1_198826',
 'rs1_198835',
 'rs1_198874',
 'rs1_199084',
 'rs1_200206',
 'rs1_200227',
 'rs1_200964',
 'rs1_200988',
 'rs1_201017',
 'rs1_201527',
 'rs1_201540',
 'rs1_204622',
 'rs1_205684',
 'rs1_210037',
 'rs1_210242',
 'rs1_210244',
 'rs1_210603',
 'rs1_211041',
 'rs1_211122',
 'rs1_211354',
 'rs1_211509',
 'rs1_211559',
 'rs1_211610',
 'rs1_211678',
 'rs1_212078',
 'rs1_212111',
 'rs1_212159',
 'rs1_212160',
 'rs1_212376',
 'rs1_212597',
 'rs1_212614',
 'rs1_212821',
 'rs1_212870',
 'rs1_213144',
 'rs1_213203',
 'rs1_213343',
 'rs1_213514',
 'rs1_213678',
 'rs1_213696',
 'rs1_214056',
 'rs1_214625',
 'rs1_215033',
 'rs1_215128',
 'rs1_215433',
 'rs1_215442',
 'rs1_215452',
 'rs1_215680',
 'rs1_215720',
 'rs1_328670',
 'rs1_328833',
 'rs1_328945',
 'rs1_329152',
 'rs1_329156',
 'rs1_329881',
 'rs1_329904',
 'rs1_329946',
 'rs1_329947',
 'rs1_335211',
 'rs1_335233',
 'rs1_335543',
 'rs1_419227',
 'rs1_419250',
 'rs1_419258',
 'rs1_420263',
 'rs1_427047',
 'rs1_427073',
 'rs1_427707',
 'rs1_427789',
 'rs1_427800',
 'rs1_427886',
 'rs1_428000',
 'rs1_428013',
 'rs1_428243',
 'rs1_428371',
 'rs1_428544',
 'rs1_561204',
 'rs1_561231',
 'rs1_561290',
 'rs1_561302',
 'rs1_561314',
 'rs1_561492',
 'rs1_561528',
 'rs1_561550',
 'rs1_561555',
 'rs1_563287',
 'rs1_563323',
 'rs1_563364',
 'rs1_563835',
 'rs1_564019',
 'rs1_564041',
 'rs1_564086',
 'rs1_564270',
 'rs1_564280',
 'rs1_564313',
 'rs1_564448',
 'rs1_564554',
 'rs1_564749',
 'rs1_564753',
 'rs1_564761',
 'rs1_564790',
 'rs1_565020',
 'rs1_565059',
 'rs1_565092',
 'rs1_565117',
 'rs1_565325',
 'rs1_565359',
 'rs1_565379',
 'rs1_565382',
 'rs1_565424',
 'rs1_565595',
 'rs1_565670',
 'rs1_565870',
 'rs1_565878',
 'rs1_565966',
 'rs1_566048',
 'rs1_566096',
 'rs1_566121',
 'rs1_566203',
 'rs1_566409',
 'rs1_566425',
 'rs1_566879',
 'rs1_566919',
 'rs1_566980',
 'rs1_567156',
 'rs1_567351',
 'rs1_567412',
 'rs1_567523',
 'rs1_567553',
 'rs1_571623',
 'rs1_571652',
 'rs1_571659',
 'rs1_571807',
 'rs1_571808',
 'rs1_571918',
 'rs1_572161',
 'rs1_572255',
 'rs1_573032',
 'rs1_573319',
 'rs1_573377',
 'rs1_573411',
 'rs1_689674',
 'rs1_689689',
 'rs1_689700',
 'rs1_689795',
 'rs1_689802',
 'rs1_689833',
 'rs1_689834',
 'rs1_690023',
 'rs1_690190',
 'rs1_691659',
 'rs1_692155',
 'rs1_693381',
 'rs1_694176',
 'rs1_694975',
 'rs1_697169',
 'rs1_700433',
 'rs1_700446',
 'rs1_700506',
 'rs1_700739',
 'rs1_701064',
 'rs1_701084',
 'rs1_711275',
 'rs1_711503',
 'rs1_711577',
 'rs1_711888',
 'rs1_711943',
 'rs1_711950',
 'rs1_712453',
 'rs1_712661',
 'rs1_712663',
 'rs1_715140',
 'rs1_715371',
 'rs1_715494',
 'rs1_715833',
 'rs1_1012314',
 'rs1_1012519',
 'rs1_1012701',
 'rs1_1013598',
 'rs1_1013631',
 'rs1_1013838',
 'rs1_1014529',
 'rs1_1016715',
 'rs1_1016786',
 'rs1_1021094',
 'rs1_1027607',
 'rs1_1028566',
 'rs1_1028830',
 'rs1_1028856',
 'rs1_1028984',
 'rs1_1029016',
 'rs1_1029018',
 'rs1_1029095',
 'rs1_1029146',
 'rs1_1029214',
 'rs1_1029315',
 'rs1_1029490',
 'rs1_1029679',
 'rs1_1029681',
 'rs1_1029772',
 'rs1_1029876',
 'rs1_1029899',
 'rs1_1029976',
 'rs1_1030015',
 'rs1_1030044',
 'rs1_1030045',
 'rs1_1030060',
 'rs1_1030066',
 'rs1_1031812',
 'rs1_1031852',
 'rs1_1032107',
 'rs1_1032114',
 'rs1_1033514',
 'rs1_1033872',
 'rs1_1033876',
 'rs1_1034627',
 'rs1_1034874',
 'rs1_1034901',
 'rs1_1034935',
 'rs1_1034939',
 'rs1_1035018',
 'rs1_1035233',
 'rs1_1035713',
 'rs1_1035735',
 'rs1_1035757',
 'rs1_1035807',
 'rs1_1035850',
 'rs1_1035870',
 'rs1_1035898',
 'rs1_1036277',
 'rs1_1037112',
 'rs1_1067926',
 'rs1_1068648',
 'rs1_1068777',
 'rs1_1068808',
 'rs1_1069042',
 'rs1_1069231',
 'rs1_1069247',
 'rs1_1069555',
 'rs1_1069686',
 'rs1_1069847',
 'rs1_1069853',
 'rs1_1069906',
 'rs1_1069942',
 'rs1_1069956',
 'rs1_1070039',
 'rs1_1070052',
 'rs1_1070058',
 'rs1_1070070',
 'rs1_1070220',
 'rs1_1070240',
 'rs1_1070282',
 'rs1_1070296',
 'rs1_1070341',
 'rs1_1070365',
 'rs1_1070392',
 'rs1_1070416',
 'rs1_1070431',
 'rs1_1070434',
 'rs1_1070482',
 'rs1_1070483',
 'rs1_1070574',
 'rs1_1070666',
 'rs1_1070743',
 'rs1_1070752',
 'rs1_1070833',
 'rs1_1070879',
 'rs1_1070966',
 'rs1_1070986',
 'rs1_1071038',
 'rs1_1071100',
 'rs1_1071205',
 'rs1_1071250',
 'rs1_1071313',
 'rs1_1071391',
 'rs1_1071433',
 'rs1_1071650',
 'rs1_1071739',
 'rs1_1071781',
 'rs1_1071843',
 'rs1_1071845',
 'rs1_1071848',
 'rs1_1071947',
 'rs1_1071977',
 'rs1_1072166',
 'rs1_1072190',
 'rs1_1072191',
 'rs1_1072279',
 'rs1_1072287',
 'rs1_1072319',
 'rs1_1072428',
 'rs1_1072497',
 'rs1_1072507',
 'rs1_1072534',
 'rs1_1072536',
 'rs1_1072563',
 'rs1_1072576',
 'rs1_1072615',
 'rs1_1072664',
 'rs1_1072666',
 'rs1_1072774',
 'rs1_1207692',
 'rs1_1207806',
 'rs1_1207822',
 'rs1_1207824',
 'rs1_1207878',
 'rs1_1207941',
 'rs1_1207946',
 'rs1_1207970',
 'rs1_1208184',
 'rs1_1208188',
 'rs1_1208880',
 'rs1_1208952',
 'rs1_1209074',
 'rs1_1209136',
 'rs1_1211062',
 'rs1_1211078',
 'rs1_1211085',
 'rs1_1211408',
 'rs1_1212276',
 'rs1_1212311',
 'rs1_1212846',
 'rs1_1212852',
 'rs1_1216365',
 'rs1_1217263',
 'rs1_1217607',
 'rs1_1217644',
 'rs1_1227275',
 'rs1_1227341',
 'rs1_1227583',
 'rs1_1227654',
 'rs1_1227948',
 'rs1_1227988',
 'rs1_1228056',
 'rs1_1228103',
 'rs1_1228158',
 'rs1_1230825',
 'rs1_1230878',
 'rs1_1231212',
 'rs1_1231308',
 'rs1_1231384',
 'rs1_1232209',
 'rs1_1232274',
 'rs1_1232341',
 'rs1_1232375',
 'rs1_1232389',
 'rs1_1233689',
 'rs1_1234776',
 'rs1_1235123',
 'rs1_1235149',
 'rs1_1235250',
 'rs1_1235390',
 'rs1_1235457',
 'rs1_1235502',
 'rs1_1235726',
 'rs1_1308546',
 'rs1_1308561',
 'rs1_1308613',
 'rs1_1492586',
 'rs1_1493667',
 'rs1_1494307',
 'rs1_1494637',
 'rs1_1496301',
 'rs1_1498979',
 'rs1_1499218',
 'rs1_1499617',
 'rs1_1499975',
 'rs1_1500010',
 'rs1_1500457',
 'rs1_1504337',
 'rs1_1504616',
 'rs1_1504751',
 'rs1_1505088',
 'rs1_1505939',
 'rs1_1506167',
 'rs1_1522810',
 'rs1_1522813',
 'rs1_1523391',
 'rs1_1523636',
 'rs1_1533055',
 'rs1_1533068',
 'rs1_1610597',
 'rs1_1610785',
 'rs1_1610800',
 'rs1_1610926',
 'rs1_1610956',
 'rs1_1611149',
 'rs1_1611172',
 'rs1_1716074',
 'rs1_1716079',
 'rs1_1716103',
 'rs1_1716154',
 'rs1_1716195',
 'rs1_1716201',
 'rs1_1716207',
 'rs1_1716246',
 'rs1_1716292',
 'rs1_1716538',
 'rs1_1716655',
 'rs1_1716760',
 'rs1_1716950',
 'rs1_1717004',
 'rs1_1717019',
 'rs1_1717083',
 'rs1_1834486',
 'rs1_1834526',
 'rs1_1834558',
 'rs1_1834608',
 'rs1_1834681',
 'rs1_1834699',
 'rs1_1834724',
 'rs1_1834997',
 'rs1_1835009',
 'rs1_1835132',
 'rs1_1835162',
 'rs1_1835206',
 'rs1_1835241',
 'rs1_1835254',
 'rs1_1835279',
 'rs1_1835376',
 'rs1_1841867',
 'rs1_1841876',
 'rs1_1841881',
 'rs1_1841883',
 'rs1_1841886',
 'rs1_1841934',
 'rs1_1841946',
 'rs1_1842005',
 'rs1_1842009',
 'rs1_1842027',
 'rs1_1842035',
 'rs1_1842047',
 'rs1_1842052',
 'rs1_1842053',
 'rs1_1842056',
 'rs1_1842059',
 'rs1_1842094',
 'rs1_1842179',
 'rs1_1842206',
 'rs1_1842265',
 'rs1_1842277',
 'rs1_1842288',
 'rs1_1842358',
 'rs1_1842363',
 'rs1_1842392',
 'rs1_1842393',
 'rs1_1842396',
 'rs1_1842442',
 'rs1_1842447',
 'rs1_1842547',
 'rs1_1842557',
 'rs1_1842589',
 'rs1_1842593',
 'rs1_1842668',
 'rs1_1842723',
 'rs1_1842748',
 'rs1_1842753',
 'rs1_1842783',
 'rs1_1842801',
 'rs1_1842824',
 'rs1_1842839',
 'rs1_1842915',
 'rs1_1842996',
 'rs1_1843003',
 'rs1_1843013',
 'rs1_1843057',
 'rs1_1843063',
 'rs1_1843080',
 'rs1_1843100',
 'rs1_1843174',
 'rs1_1843513',
 'rs1_1843514',
 'rs1_1919247',
 'rs1_1919296',
 'rs1_1919452',
 'rs1_1919504',
 'rs1_1920072',
 'rs1_1920087',
 'rs1_1920088',
 'rs1_1920098',
 'rs1_1920793',
 'rs1_1920816',
 'rs1_1921060',
 'rs1_1921450',
 'rs1_1921520',
 'rs1_1921579',
 'rs1_1921627',
 'rs1_1921670',
 'rs1_1921737',
 'rs1_1938641',
 'rs1_1938654',
 'rs1_1938666',
 'rs1_1938667',
 'rs1_1938669',
 'rs1_1938695',
 'rs1_1938715',
 'rs1_1938716',
 'rs1_1938772',
 'rs1_1938832',
 'rs1_1938841',
 'rs1_1938844',
 'rs1_1938846',
 'rs1_1938946',
 'rs1_1938952',
 'rs1_1938953',
 'rs1_1938958',
 'rs1_1939026',
 'rs1_1939030',
 'rs1_1939103',
 'rs1_1939106',
 'rs1_1939217',
 'rs1_1939273',
 'rs1_1939295',
 'rs1_1941933',
 'rs1_1941934',
 'rs1_1941939',
 'rs1_1941940',
 'rs1_1941945',
 'rs1_1941958',
 'rs1_1941964',
 'rs1_1941968',
 'rs1_1941981',
 'rs1_1941982',
 'rs1_1942011',
 'rs1_1942028',
 'rs1_1942052',
 'rs1_1942057',
 'rs1_1942063',
 'rs1_1942116',
 'rs1_1942124',
 'rs1_1942125',
 'rs1_1942126',
 'rs1_1942152',
 'rs1_1942153',
 'rs1_1942162',
 'rs1_1942194',
 'rs1_1942239',
 'rs1_1942244',
 'rs1_1942293',
 'rs1_1942305',
 'rs1_1942317',
 'rs1_1942434',
 'rs1_1942446',
 'rs1_1942463',
 'rs1_1942470',
 'rs1_1942478',
 'rs1_1942479',
 'rs1_1942503',
 'rs1_1942524',
 'rs1_1942603',
 'rs1_1942604',
 'rs1_1942636',
 'rs1_1942656',
 'rs1_2019608',
 'rs1_2019636',
 'rs1_2019684',
 'rs1_2019771',
 'rs1_2019812',
 'rs1_2019826',
 'rs1_2019827',
 'rs1_2019831',
 'rs1_2019901',
 'rs1_2019915',
 'rs1_2019918',
 'rs1_2020065',
 'rs1_2020129',
 'rs1_2020164',
 'rs1_2020191',
 'rs1_2020229',
 'rs1_2020276',
 'rs1_2020356',
 'rs1_2020539',
 'rs1_2020757',
 'rs1_2020815',
 'rs1_2020864',
 'rs1_2020872',
 'rs1_2020896',
 'rs1_2021013',
 'rs1_2021385',
 'rs1_2021386',
 'rs1_2021427',
 'rs1_2021454',
 'rs1_2021457',
 'rs1_2026935',
 'rs1_2026964',
 'rs1_2026967',
 'rs1_2026975',
 'rs1_2026978',
 'rs1_2027013',
 'rs1_2027057',
 'rs1_2027073',
 'rs1_2027128',
 'rs1_2027165',
 'rs1_2027218',
 'rs1_2027219',
 'rs1_2027226',
 'rs1_2027231',
 'rs1_2027247',
 'rs1_2027261',
 'rs1_2027305',
 'rs1_2027332',
 'rs1_2027350',
 'rs1_2027362',
 'rs1_2027547',
 'rs1_2027701',
 'rs1_2027746',
 'rs1_2027788',
 'rs1_2031946',
 'rs1_2031976',
 'rs1_2032012',
 'rs1_2032048',
 'rs1_2032060',
 'rs1_2032255',
 'rs1_2032407',
 'rs1_2032811',
 'rs1_2032883',
 'rs1_2033005',
 'rs1_2033116',
 'rs1_2033117',
 'rs1_2033146',
 'rs1_2033151',
 'rs1_2033177',
 'rs1_2033213',
 'rs1_2033217',
 'rs1_2033235',
 'rs1_2033258',
 'rs1_2033264',
 'rs1_2033265',
 'rs1_2033325',
 'rs1_2033335',
 'rs1_2033369',
 'rs1_2033370',
 'rs1_2033379',
 'rs1_2033421',
 'rs1_2033461',
 'rs1_2033481',
 'rs1_2033736',
 'rs1_2033749',
 'rs1_2033850',
 'rs1_2033899',
 'rs1_2033942',
 'rs1_2033989',
 'rs1_2033990',
 'rs1_2033997',
 'rs1_2034015',
 'rs1_2034039',
 'rs1_2034053',
 'rs1_2034083',
 'rs1_2034084',
 'rs1_2104791',
 'rs1_2104835',
 'rs1_2104864',
 'rs1_2104865',
 'rs1_2104867',
 'rs1_2104909',
 'rs1_2104939',
 'rs1_2105005',
 'rs1_2105035',
 'rs1_2105050',
 'rs1_2105062',
 'rs1_2105101',
 'rs1_2105152',
 'rs1_2105236',
 'rs1_2105254',
 'rs1_2105261',
 'rs1_2105394',
 'rs1_2105442',
 'rs1_2105499',
 'rs1_2105519',
 'rs1_2105521',
 'rs1_2105529',
 'rs1_2105535',
 'rs1_2105550',
 'rs1_2105583',
 'rs1_2105613',
 'rs1_2105619',
 'rs1_2105694',
 'rs1_2105739',
 'rs1_2105773',
 'rs1_2105847',
 'rs1_2105877',
 'rs1_2105895',
 'rs1_2105898',
 'rs1_2105931',
 'rs1_2106039',
 'rs1_2106075',
 'rs1_2106189',
 'rs1_2106222',
 'rs1_2106243',
 'rs1_2106258',
 'rs1_2106292',
 'rs1_2106309',
 'rs1_2106317',
 'rs1_2106328',
 'rs1_2106374',
 'rs1_2106411',
 'rs1_2106436',
 'rs1_2106460',
 'rs1_2106473',
 'rs1_2106476',
 'rs1_2106507',
 'rs1_2106522',
 'rs1_2106528',
 'rs1_2106529',
 'rs1_2106531',
 'rs1_2109232',
 'rs1_2109339',
 'rs1_2109455',
 'rs1_2109991',
 'rs1_2110046',
 'rs1_2110058',
 'rs1_2110097',
 'rs1_2110186',
 'rs1_2110187',
 'rs1_2110259',
 'rs1_2110361',
 'rs1_2110529',
 'rs1_2110533',
 'rs1_2110637',
 'rs1_2110705',
 'rs1_2110784',
 'rs1_2110807',
 'rs1_2110810',
 'rs1_2110817',
 'rs1_2110960',
 'rs1_2111061',
 'rs1_2111101',
 'rs1_2111123',
 'rs1_2111135',
 'rs1_2111160',
 'rs1_2111241',
 'rs1_2111337',
 'rs1_2111345',
 'rs1_2111575',
 'rs1_2111581',
 'rs1_2111582',
 'rs1_2111609',
 'rs1_2111704',
 'rs1_2111715',
 'rs1_2113110',
 'rs1_2113180',
 'rs1_2154260',
 'rs1_2154277',
 'rs1_2154291',
 'rs1_2154358',
 'rs1_2154412',
 'rs1_2154496',
 'rs1_2154577',
 'rs1_2154633',
 'rs1_2154656',
 'rs1_2154665',
 'rs1_2154693',
 'rs1_2154956',
 'rs1_2154983',
 'rs1_2155613',
 'rs1_2155622',
 'rs1_2155646',
 'rs1_2155647',
 'rs1_2155735',
 'rs1_2155942',
 'rs1_2155977',
 'rs1_2156005',
 'rs1_2156065',
 'rs1_2156075',
 'rs1_2156092',
 'rs1_2156128',
 'rs1_2156237',
 'rs1_2157326',
 'rs1_2157457',
 'rs1_2157611',
 'rs1_2157661',
 'rs1_2157734',
 'rs1_2157807',
 'rs1_2157935',
 'rs1_2157991',
 'rs1_2158040',
 'rs1_2158057',
 'rs1_2158281',
 'rs1_2158420',
 'rs1_2158498',
 'rs1_2158534',
 'rs1_2159217',
 'rs1_2159237',
 'rs1_2159238',
 'rs1_2159288',
 'rs1_2159299',
 'rs1_2159377',
 'rs1_2159495',
 'rs1_2159559',
 'rs1_2159630',
 'rs1_2159631',
 'rs1_2159739',
 'rs1_2159834',
 'rs1_2159904',
 'rs1_2159994',
 'rs1_2160012',
 'rs1_2160189',
 'rs1_2160261',
 'rs1_2160279',
 'rs1_2160296',
 'rs1_2160538',
 'rs1_2160553',
 'rs1_2160669',
 'rs1_2160673',
 'rs1_2161093',
 'rs1_2161120',
 'rs1_2161183',
 'rs1_2161260',
 'rs1_2161339',
 'rs1_2161369',
 'rs1_2161372',
 'rs1_2161381',
 'rs1_2161403',
 'rs1_2161414',
 'rs1_2161496',
 'rs1_2161710',
 'rs1_2161735',
 'rs1_2162777',
 'rs1_2162802',
 'rs1_2162835',
 'rs1_2162861',
 'rs1_2162871',
 'rs1_2162951',
 'rs1_2163061',
 'rs1_2163302',
 'rs1_2163449',
 'rs1_2163468',
 'rs1_2163480',
 'rs1_2163522',
 'rs1_2163564',
 'rs1_2163678',
 'rs1_2163733',
 'rs1_2163846',
 'rs1_2163869',
 'rs1_2163998',
 'rs1_2164017',
 'rs1_2164044',
 'rs1_2164145',
 'rs1_2164258',
 'rs1_2164275',
 'rs1_2164512',
 'rs1_2164701',
 'rs1_2164744',
 'rs1_2164783',
 'rs1_2164828',
 'rs1_2164915',
 'rs1_2164994',
 'rs1_2165226',
 'rs1_2165245',
 'rs1_2165259',
 'rs1_2165320',
 'rs1_2165322',
 'rs1_2165363',
 'rs1_2165463',
 'rs1_2165619',
 'rs1_2165631',
 'rs1_2165688',
 'rs1_2166360',
 'rs1_2166399',
 'rs1_2166774',
 'rs1_2168822',
 'rs1_2169146',
 'rs1_2170177',
 'rs1_2170322',
 'rs1_2284866',
 'rs1_2284867',
 'rs1_2285176',
 'rs1_2285190',
 'rs1_2285209',
 ...]

Same for SNPs. Right now we only care about their position. Instead of using 16GB to load the data we use less than 500Mb!!!!

In [39]:
snp_matrix_imputed_raw = pd.read_table(src + file_snp_imp, usecols=high_rs)
snp_matrix_imputed_raw = snp_matrix_imputed_raw*2
snp_matrix_imputed_raw

,rs1_5698946,rs1_5698973,rs1_5698991,rs1_5698994,rs1_5699162,rs1_5699203,rs1_9355640,rs1_11304590,rs1_11304666,rs1_11304694,...,rs10_144991120,rs10_147354508,rs10_147354557,rs10_147354610,rs10_147354614,rs10_147354710,rs10_147354719,rs10_147354742,rs10_147354782,rs10_147354788
0,2,2.0,2,2,2,0.0,2,2,2,2,...,2,2,2.0,2.0,2.0,2.0,2,2.0,2.0,2.0
1,2,2.0,2,2,2,2.0,2,2,0,0,...,2,2,2.0,2.0,2.0,2.0,2,2.0,2.0,2.0
2,2,0.0,2,2,2,2.0,2,2,2,2,...,2,2,2.0,2.0,2.0,2.0,2,2.0,2.0,2.0
3,2,2.0,2,2,2,0.0,2,2,2,2,...,2,2,2.0,2.0,2.0,2.0,2,2.0,2.0,2.0
4,2,2.0,2,2,2,2.0,2,2,2,2,...,2,2,2.0,2.0,2.0,2.0,2,2.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,2,NaN,2,2,2,2.0,2,2,2,2,...,2,2,2.0,2.0,2.0,2.0,2,2.0,2.0,2.0
938,2,2.0,2,2,2,0.0,2,2,2,2,...,2,2,2.0,2.0,2.0,0.0,2,2.0,2.0,0.0
939,2,0.0,2,2,2,2.0,2,2,2,2,...,2,2,2.0,0.0,0.0,2.0,2,2.0,0.0,2.0
940,2,2.0,2,2,2,0.0,2,2,2,2,...,2,2,2.0,2.0,2.0,2.0,2,2.0,2.0,2.0
941,2,2.0,2,2,2,0.0,2,2,2,2,...,2,2,2.0,2.0,2.0,2.0,2,2.0,2.0,2.0

In [60]:
snp_high_z_alt = pd.read_csv(src+file_snp_high_z, nrows=10)

In [48]:
snp_matrix_imputed_raw['cultivars'] = snp_high_z_alt.columns.values[4:]
snp_matrix_imputed_raw

,rs1_5698946,rs1_5698973,rs1_5698991,rs1_5698994,rs1_5699162,rs1_5699203,rs1_9355640,rs1_11304590,rs1_11304666,rs1_11304694,...,rs10_147354508,rs10_147354557,rs10_147354610,rs10_147354614,rs10_147354710,rs10_147354719,rs10_147354742,rs10_147354782,rs10_147354788,cultivars
0,2,2.0,2,2,2,0.0,2,2,2,2,...,2,2.0,2.0,2.0,2.0,2,2.0,2.0,2.0,764
1,2,2.0,2,2,2,2.0,2,2,0,0,...,2,2.0,2.0,2.0,2.0,2,2.0,2.0,2.0,779
2,2,0.0,2,2,2,2.0,2,2,2,2,...,2,2.0,2.0,2.0,2.0,2,2.0,2.0,2.0,787
3,2,2.0,2,2,2,0.0,2,2,2,2,...,2,2.0,2.0,2.0,2.0,2,2.0,2.0,2.0,790
4,2,2.0,2,2,2,2.0,2,2,2,2,...,2,2.0,2.0,2.0,2.0,2,2.0,2.0,2.0,793
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,2,NaN,2,2,2,2.0,2,2,2,2,...,2,2.0,2.0,2.0,2.0,2,2.0,2.0,2.0,Yong_28
938,2,2.0,2,2,2,0.0,2,2,2,2,...,2,2.0,2.0,2.0,0.0,2,2.0,2.0,0.0,Yu796_NS
939,2,0.0,2,2,2,2.0,2,2,2,2,...,2,2.0,0.0,0.0,2.0,2,2.0,0.0,2.0,ZS01250
940,2,2.0,2,2,2,0.0,2,2,2,2,...,2,2.0,2.0,2.0,2.0,2,2.0,2.0,2.0,ZS1791
941,2,2.0,2,2,2,0.0,2,2,2,2,...,2,2.0,2.0,2.0,2.0,2,2.0,2.0,2.0,ZS635

In [54]:
snp_matrix_imputed_raw = snp_matrix_imputed_raw.set_index('cultivars').T
snp_matrix_imputed_raw

cultivars,764,779,787,790,793,904,911,912,1538,2369,...,YANG,YE_4,YE-CHI-HUNG,YELLOW_3-4,YING-55,Yong_28,Yu796_NS,ZS01250,ZS1791,ZS635
rs1_5698946,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
rs1_5698973,2.0,2.0,0.0,2.0,2.0,2.0,2.0,0.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,2.0
rs1_5698991,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
rs1_5698994,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
rs1_5699162,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
rs10_147354710,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,0.0,2.0,2.0,2.0
rs10_147354719,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
rs10_147354742,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
rs10_147354782,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,NaN,2.0,2.0,2.0,2.0,2.0,0.0,2.0,2.0
rs10_147354788,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,0.0,2.0,2.0,2.0

For each chromosome, select only those genes and snps present in such chromosome.

Sort the genes by left position. Loop only once through all the SNPs and gene regions. We assume that genes do not overlap.

Keep a list with all the SNP indices that are contained in highly varying genes.

The SNP indices are unfortunately not global but they are with respect to their chromosome. They need to be shifted appropriately.

array([ 1,  1,  1, ..., 10, 10, 10])

In [62]:
snps = snp_matrix_imputed_raw.assign(chrom=snp_high_z.chrom.values, pos=snp_high_z.pos.values)
cols = snps.columns.values[:-2]
cols = np.insert(cols,0,'pos')
cols = np.insert(cols,0,'chrom')
snps = snps[cols]
snps.to_csv(dst + 'high_z_snps_tassel.csv', index=False)

In [63]:
snps.to_csv(dst + 'high_z_snps_tassel_NA.csv', na_rep='NA', index=False)